This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning style file ./MidThesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file MidThesis.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file MidThesis.acr....done (6 lines written, 0 warnings).
Output written in MidThesis.acr.
Transcript written in MidThesis.alg.
